// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	pgx "github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// UserDb is an autogenerated mock type for the userDb type
type UserDb struct {
	mock.Mock
}

type UserDb_Expecter struct {
	mock *mock.Mock
}

func (_m *UserDb) EXPECT() *UserDb_Expecter {
	return &UserDb_Expecter{mock: &_m.Mock}
}

// Query provides a mock function with given fields: ctx, sql, args
func (_m *UserDb) Query(ctx context.Context, sql string, args ...interface{}) (pgx.Rows, error) {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 pgx.Rows
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Rows); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, ...interface{}) error); ok {
		r1 = rf(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserDb_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type UserDb_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *UserDb_Expecter) Query(ctx interface{}, sql interface{}, args ...interface{}) *UserDb_Query_Call {
	return &UserDb_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *UserDb_Query_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *UserDb_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *UserDb_Query_Call) Return(_a0 pgx.Rows, _a1 error) *UserDb_Query_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

// QueryRow provides a mock function with given fields: ctx, sql, args
func (_m *UserDb) QueryRow(ctx context.Context, sql string, args ...interface{}) pgx.Row {
	var _ca []interface{}
	_ca = append(_ca, ctx, sql)
	_ca = append(_ca, args...)
	ret := _m.Called(_ca...)

	var r0 pgx.Row
	if rf, ok := ret.Get(0).(func(context.Context, string, ...interface{}) pgx.Row); ok {
		r0 = rf(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}

	return r0
}

// UserDb_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type UserDb_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...interface{}
func (_e *UserDb_Expecter) QueryRow(ctx interface{}, sql interface{}, args ...interface{}) *UserDb_QueryRow_Call {
	return &UserDb_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]interface{}{ctx, sql}, args...)...)}
}

func (_c *UserDb_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...interface{})) *UserDb_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(context.Context), args[1].(string), variadicArgs...)
	})
	return _c
}

func (_c *UserDb_QueryRow_Call) Return(_a0 pgx.Row) *UserDb_QueryRow_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewUserDb interface {
	mock.TestingT
	Cleanup(func())
}

// NewUserDb creates a new instance of UserDb. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUserDb(t mockConstructorTestingTNewUserDb) *UserDb {
	mock := &UserDb{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
