// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// LoginHandler is an autogenerated mock type for the loginHandler type
type LoginHandler struct {
	mock.Mock
}

type LoginHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *LoginHandler) EXPECT() *LoginHandler_Expecter {
	return &LoginHandler_Expecter{mock: &_m.Mock}
}

// Authenticate provides a mock function with given fields:
func (_m *LoginHandler) Authenticate() func(http.ResponseWriter, *http.Request) {
	ret := _m.Called()

	var r0 func(http.ResponseWriter, *http.Request)
	if rf, ok := ret.Get(0).(func() func(http.ResponseWriter, *http.Request)); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(func(http.ResponseWriter, *http.Request))
		}
	}

	return r0
}

// LoginHandler_Authenticate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authenticate'
type LoginHandler_Authenticate_Call struct {
	*mock.Call
}

// Authenticate is a helper method to define mock.On call
func (_e *LoginHandler_Expecter) Authenticate() *LoginHandler_Authenticate_Call {
	return &LoginHandler_Authenticate_Call{Call: _e.mock.On("Authenticate")}
}

func (_c *LoginHandler_Authenticate_Call) Run(run func()) *LoginHandler_Authenticate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LoginHandler_Authenticate_Call) Return(_a0 func(http.ResponseWriter, *http.Request)) *LoginHandler_Authenticate_Call {
	_c.Call.Return(_a0)
	return _c
}

type mockConstructorTestingTNewLoginHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewLoginHandler creates a new instance of LoginHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLoginHandler(t mockConstructorTestingTNewLoginHandler) *LoginHandler {
	mock := &LoginHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
